# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
# When enabled, the Configuration Cache allows Gradle to skip the configuration
# phase entirely if nothing that affects the build configuration (such as build scripts)
# has changed. Additionally, Gradle applies performance optimizations to task execution.
org.gradle.configuration-cache=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
android.disallowKotlinSourceSets=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
android.enableR8.fullMode=false
production.server.url=https://server.valumeyapp.lol/service/
qa.server.url=https://server.valumeyapp.lol/service/
preferences.encryption = ValuApplication-preferences
pinning.encryption = sha256/Um5tYMDuvTqvUPiXXX3hfO29F4jxQ9s2Y2iz2kMAgCs=
pinning.root = sha256/mEflZT5enoR1FuXLgYYGqnVEoZvmf9c2bVBpiOjYQ0c=
hash.one = 42:8E:92:AF:4F:C5:56:46:D2:8B:DC:53:59:AE:1E:4E:43:69:2E:D4:69:94:8D:FB:02:01:33:66:1F:AF:E5:EF
hash.two = DD:05:1D:91:9F:79:AB:A5:31:06:B3:1E:0B:F1:F7:71:64:1E:C9:14:CC:B1:82:1C:5C:A1:2C:8C:1C:AB:ED:7B