package com.tayler.entity

data class ParamModel (
    var uid: String? = "",
    var title: String = "",
    var description: String = "",
    var idMovie: String = "",
    var enableCategory: Boolean = false,
    var phone: String = "935096444",
    var textWelcome: String = "",
    var hourStart: String? = "",
    var hourEnd: String? = "",
    var limitDistance: String? = "5",
    var countProduct: String? = "100",
    var styleValu: String = "0",
    var bgService: Boolean = false,
    var bgToolbar: Boolean? = false,
    var countryCode: String? = "PE",
    var blocking: Boolean? = null,
    var idIcon: String = "Principal",
    var idFacebook: String = "61590557890653",
    var idYoutube: String? = "xH6qsMpA7NM",
    var session: Boolean = false,
    var urlImage: String? = "",
    var idIconOld: String = "0",
)